DROP TABLE E_COSTS;
DROP TABLE M_COST_CODE;

CREATE TABLE E_COSTS
(
COST_ID         INT,
COST_VALUE      DECIMAL(10,2) NOT NULL,
COST_YEAR       INT NOT NULL,
COST_MONTH      INT NOT NULL,
COST_CODE       INT NOT NULL,
COST_COMMENT    VARCHAR(255),
PRIMARY KEY (COST_ID)
);

CREATE TABLE M_COST_CODE
(
COST_CODE                 INT,
COST_CODE_DESCRIPTION     VARCHAR(255) NOT NULL,
PRIMARY KEY (COST_CODE)
);

ALTER TABLE E_COSTS ADD CONSTRAINT E_COSTS_FK1
FOREIGN KEY (COST_CODE) REFERENCES M_COST_CODE (COST_CODE);

ALTER TABLE E_COSTS ADD CONSTRAINT E_COSTS_CH1 CHECK (COST_YEAR > 2013);
ALTER TABLE E_COSTS ADD CONSTRAINT E_COSTS_CH2 CHECK (COST_YEAR < 2222);
ALTER TABLE E_COSTS ADD CONSTRAINT E_COSTS_CH3 CHECK (COST_MONTH > 0);
ALTER TABLE E_COSTS ADD CONSTRAINT E_COSTS_CH4 CHECK (COST_MONTH < 13);


INSERT INTO M_COST_CODE VALUES (1,'Alkoholische Getränke und Tabakwaren');
INSERT INTO M_COST_CODE VALUES (2,'Andere Waren und Dienstleistungen');
INSERT INTO M_COST_CODE VALUES (3,'Bekleidung und Schuhe');
INSERT INTO M_COST_CODE VALUES (4,'Bildungswesen');
INSERT INTO M_COST_CODE VALUES (5,'Einrichtungsgegenstände');
INSERT INTO M_COST_CODE VALUES (6,'Freizeit, Unterhaltung, Kultur');
INSERT INTO M_COST_CODE VALUES (7,'Gastronomie');
INSERT INTO M_COST_CODE VALUES (8,'Geldanlage');
INSERT INTO M_COST_CODE VALUES (9,'Geschenke');
INSERT INTO M_COST_CODE VALUES (10,'Gesundheitspflege');
INSERT INTO M_COST_CODE VALUES (11,'Nachrichtenübermittlung');
INSERT INTO M_COST_CODE VALUES (12,'Nahrungsmittel und alkoholfreie Getränke');
INSERT INTO M_COST_CODE VALUES (13,'Tanken');
INSERT INTO M_COST_CODE VALUES (14,'Verkehr ohne Tanken');
INSERT INTO M_COST_CODE VALUES (15,'Versicherung');
INSERT INTO M_COST_CODE VALUES (16,'Wohnungsmieten, Energie');